export const ACTION_TYPE = {
  SET_THEME: 'SET_THEME',
  SET_USER: 'SET_USER',
  SET_HOTELS: 'SET_HOTELS',
  SET_COMMENTS: 'SET_COMMENTS',
  SET_ORDERED_HOTELS: 'SET_ORDERED_HOTELS',
  RESET_USER: 'RESET_USER',
  RESET_HOTELS: 'RESET_HOTELS',
};
